apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-service
  labels:
    app: ship-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship-service
  template:
    metadata:
      labels:
        app: ship-service
    spec:
      containers:
      - name: ship-service
        image: {{ .Values.image }}
        ports:
        - containerPort: 8442
