---
image: ubuntu

stages:
  - test
  - build
  - deploy

test donut:
  variables:
    SERVICE_NAME: donut-service
  extends: .test-go

build-and-push donut:
  variables:
    SERVICE_NAME: donut-service
  extends: .build-and-push

deploy donut:
  variables:
    SERVICE_NAME: donut-service
  extends: .deploy

.test-go:
  stage: test
  image: golang:1.13-alpine3.10
  script:
    - cd $SERVICE_NAME
    - echo test
  # only:
  #   changes:
  #     - $SERVICE_NAME/**/*

.build-and-push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - export APP_VERSION=$(cat helm/charts/$SERVICE_NAME/Chart.yaml | grep appVersion | awk -F' ' '{print $2}')
    - echo ${GCLOUD_SERVICE_KEY} | base64 -d > ${HOME}/gcloud-service-key.json
    - docker login -u _json_key -p "$(cat ${HOME}/gcloud-service-key.json)" https://gcr.io
  script:
    - cd $SERVICE_NAME
    - docker build . -t gcr.io/kube-gke-terra/$SERVICE_NAME:${APP_VERSION}-${CI_COMMIT_SHORT_SHA}
    - docker push gcr.io/kube-gke-terra/$SERVICE_NAME:${APP_VERSION}-${CI_COMMIT_SHORT_SHA}
  only:
    changes:
      - $SERVICE_NAME/**/*
      - helm/charts/$SERVICE_NAME/**/*

.deploy:
  stage: deploy
  image: punkupoz/cloud-utils:v1.2.0
  before_script:
    - export APP_VERSION=$(cat helm/charts/$SERVICE_NAME/Chart.yaml | grep appVersion | awk -F' ' '{print $2}')
    - echo ${GCLOUD_SERVICE_KEY} | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project ${GCP_PROJECT_ID}
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${CLUSTER_ZONE} --project ${GCP_PROJECT_ID}
  script:
    - helm upgrade $SERVICE_NAME-prod --install ./helm/charts/$SERVICE_NAME 
      --set imageProd=gcr.io/kube-gke-terra/$SERVICE_NAME:${APP_VERSION}-${CI_COMMIT_SHORT_SHA}
      --set env_codename=prod
  only:
    changes:
      - helm/charts/$SERVICE_NAME/**/*