apiVersion: v1
kind: Service
metadata:
  name: ship-service
  labels:
    app: ship-service
spec:
  clusterIP: None
  ports:
    - port: 8442
      name: ship-service
  selector:
    app: ship-service